version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.4.1-node-browsers
        environment: 
        - APP_DEBUG: true
        - APP_ENV: testing
        - DB_CONNECTION: mysql
        - DB_DATABASE: room_test
        - DB_USERNAME: 'root'
        - DB_PASSWORD: 'sakarice6123'

      - image: circleci/mysql:latest
        environment: 
        - MYSQL_ALLOW_EMPTY_PASSWORD: true
        - MYSQL_DATABASE: room_test
        - MYSQL_ROOT_PASSWORD: 'sakarice6123'
        command:
          mysqld --default-authentication-plugin=mysql_native_password
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
 
      - run: composer install -n --prefer-dist
 
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
 
      - run: echo "APP_KEY=" > .env.testing
      - run: php artisan key:generate
      - run: sudo apt-get install default-mysql-client
      - run: mysql --version
      - run: mysql -h 127.0.0.1 -u root -psakarice6123 room_test --execute="show databases"
      - run: mysql -h 127.0.0.1 -u root -psakarice6123 room_test --execute="SELECT user, host FROM mysql.user ORDER BY user, host"
      - run: php artisan migrate

      - run:
          name: Run test
          command: 'echo HellooooooWorld'

      - run:
          name: PHP Test
          command: 'php artisan test'
  #EC2に接続し、デプロイ
  deploy: 
    machine: 
      image: circleci/classic:edge 
    steps: 
      #CircleCIに登録したSSHキーを呼び出す
      - add_ssh_keys: 
      - run: ssh ubuntu@35.73.109.33 'cd /usr/local/src/app/Room/docker-for-app-Room/backend/Room'
      - run: ssh ubuntu@35.73.109.33 'cd /usr/local/src/app/Room/docker-for-app-Room/backend/Room && pwd'
      - run: ssh ubuntu@35.73.109.33 'cd /usr/local/src/app/Room/docker-for-app-Room/backend/Room && sudo git pull origin master'

workflows:
  version: 2 
  build_and_deploy: 
    jobs: 
      - build 
      - deploy: 
          requires: 
            - build
        # circleci-project-setupブランチがpushされた場合のみdeployするようにする。
          filters:
            branches:
              only: master
              